// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6UMl7p5z59q7K4g57Z_H5fdebXitwLPM',
    appId: '1:1038329009073:web:3aba3fa835a65d0119a390',
    messagingSenderId: '1038329009073',
    projectId: 'mannkibaat-a49b1',
    authDomain: 'mannkibaat-a49b1.firebaseapp.com',
    storageBucket: 'mannkibaat-a49b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFe5qsxGRzwii1w6p8D4PI-H2YITiXIMo',
    appId: '1:1038329009073:android:2a1ad43d878d9b2b19a390',
    messagingSenderId: '1038329009073',
    projectId: 'mannkibaat-a49b1',
    storageBucket: 'mannkibaat-a49b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC38BztUZOTmnFvN8pUEZ5UViYzskIrTrI',
    appId: '1:1038329009073:ios:a7ccf4d5c0d9a5ee19a390',
    messagingSenderId: '1038329009073',
    projectId: 'mannkibaat-a49b1',
    storageBucket: 'mannkibaat-a49b1.appspot.com',
    iosClientId:
        '1038329009073-nf7fuedunnr5uavlks99vh72ftn74bts.apps.googleusercontent.com',
    iosBundleId: 'com.example.mannkibaat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC38BztUZOTmnFvN8pUEZ5UViYzskIrTrI',
    appId: '1:1038329009073:ios:a7ccf4d5c0d9a5ee19a390',
    messagingSenderId: '1038329009073',
    projectId: 'mannkibaat-a49b1',
    storageBucket: 'mannkibaat-a49b1.appspot.com',
    iosClientId:
        '1038329009073-nf7fuedunnr5uavlks99vh72ftn74bts.apps.googleusercontent.com',
    iosBundleId: 'com.example.mannkibaat',
  );
}
